version: '2'

services:
    twitter-bot:
        build: .
        volumes:
            - ./:/app
        ports:
            - '8000:3000'
        env_file:
            - .env_production
        links:
            - mysql
        command: ['npm', 'run', 'prod']
    mysql:
        image: mysql:5.7
        ports:
            - 8306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=twitterbot_db
            - MYSQL_USER=twitterbot_user
            - MYSQL_PASSWORD=twitterbotuser
volumes:
    mysql-data: {}
